[appearance]
spacing = "compact"

[appearance.themes]
system_theme = false
theme = { custom = { name = "Catppuccin Mocha", path = "/Users/daw/.warp/themes/catppuccin_mocha.yml" } }
selected_system_themes = {
  dark = { custom = { name = "Catppuccin Frappe", path = "/Users/daw/.warp/themes/catppuccin_frappe.yml" } },
  light = { custom = { name = "Catppuccin Latte", path = "/Users/daw/.warp/themes/catppuccin_latte.yml" } },
}

[appearance.vertical_tabs]
enabled = false
show_panel_in_restored_windows = false
use_latest_prompt_as_title = false

[appearance.icon]
app_icon = "aurora"

[appearance.text]
notebook_font_size = 14.0
font_size = 16.0
font_name = "Liga SFMono Nerd Font"
match_ai_font = true
ai_font_name = "Liga SFMono Nerd Font"
use_thin_strokes = "always"
ligature_rendering_enabled = true
line_height_ratio = 1.0
enforce_minimum_contrast = "only_named_colors"

[appearance.window]
override_opacity = 70
override_blur = 10
zoom_level = 150

[appearance.panes]
should_dim_inactive_panes = true
focus_pane_on_hover = false

[appearance.tabs]
workspace_decoration_visibility = "always_show"
preserve_active_tab_color = false

[appearance.tabs.header_toolbar_chip_selection]

[appearance.tabs.header_toolbar_chip_selection.custom]
left = ["tabs_panel", "tools_panel"]
right = ["code_review", "notifications_mailbox"]

[appearance.cursor]
cursor_display_type = "bar"

[appearance.full_screen_apps]
alt_screen_padding = { custom = { uniform_padding = 0.0 } }

[code]

[code.editor]
show_code_review_button = true
show_project_explorer = false
show_global_search = false

[warp_drive]
enabled = false

[agents]

[agents.third_party]
should_render_cli_agent_toolbar = false

[agents.warp_agent]
is_any_ai_enabled = false

[agents.warp_agent.other]
show_agent_notifications = true

[terminal]

[terminal.input]
input_box_type_setting = "classic"
honor_ps1 = true

[notifications]
toast_duration_secs = 8

[notifications.preferences]
is_agent_task_completed_enabled = true
is_long_running_enabled = true
is_needs_attention_enabled = true
is_password_prompt_enabled = true
long_running_threshold = 30
mode = "dismissed"
play_notification_sound = true

[privacy]

[privacy.secret_redaction]
enabled = false

[general]
quit_on_last_window_closed = true
